name: Update data
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' # Run every day

jobs: 
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Fetch JSON files
      run: ./update.sh
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Niek
        author_email: mail@niekvandermaas.nl
        message: "Updated Tesla data"
        add: "*"
